# Generated by Django 3.2.14 on 2022-07-18 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookrecommender', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='book_ratings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=0)),
                ('book_isbn', models.CharField(max_length=80)),
                ('book_rating', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_isbn', models.CharField(max_length=80, unique=True)),
                ('book_title', models.CharField(max_length=250)),
                ('book_author', models.CharField(max_length=250)),
                ('publisher', models.CharField(max_length=250)),
                ('imagine_url_s', models.CharField(max_length=500)),
                ('imagine_url_m', models.CharField(max_length=500)),
                ('imagine_url_l', models.CharField(max_length=500)),
            ],
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
