# Generated by Django 3.2.14 on 2022-07-19 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookrecommender', '0002_auto_20220718_1759'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='year_of_publication',
            field=models.IntegerField(default=0),
        ),
    ]
