# Generated by Django 3.2.14 on 2022-07-19 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookrecommender', '0003_books_year_of_publication'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='year_of_publication',
        ),
    ]
